spring:
  application:
    sky-cloud-eureka-server

server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/